# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:8.11

# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-a-service
services:
# - redis:latest
  - postgres:9.5

variables:
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - node_modules/

test_async:
  variables:
    NODE_ENV: testing
    BLOG_DB_HOST: postgres
  before_script:
    - npm install
    - cd packages/api && npm install && cd ../..
    - cd packages/sdk && npm install && cd ../..
  script:
    - PATH="./node_modules/.bin:./packages/api/node_modules/.bin:./packages/sdk/node_modules/.bin:$PATH" yarn test
