version: '3'
services:
  web:
    build: .
    command: bash -c "npm install; npm run nodemon;"
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    links:
      - mongo
  mongo:
    image: mongo:4.0.0
    ports:
      - "27017:27017"