version: "3.2"

services:
  dev:
    image: marcoonroad/spot-challenge
    build: .
    privileged: true
    ports:
      - "3000:3000"
      - "3001:3001"
      - "3002:3002"
    networks:
      - postgres
    depends_on:
      - db
    environment:
      - DEBUG="*,*:*"
      - BLOG_DB_PORT=5444
    command: ["run", "start:dev"]

  test:
    image: marcoonroad/spot-challenge
    build: .
    privileged: true
    networks:
      - postgres
    depends_on:
      - db
    environment:
      - NODE_ENV="testing"
      - BLOG_DB_PORT=5444
    command: ["test"]

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5444:5432"
    volumes:
      - ./data/postgres:/var/lib/postgres
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge
